# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "go-silky"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/go-silky"

[[annotations]]
path = ["**.gitignore", ".pre-commit-config.yaml", ".github/workflows/**", "**/go.mod", "**/go.sum", "**/*.json", "**/*.yaml", "**/*.md", "**/*.gif", "**/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
