name: Silky Package CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'cmd/ide/**'
  pull_request:
    paths-ignore:
      - 'cmd/ide/**'

jobs:
  reuse-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  test:
    runs-on: ubuntu-latest
    needs: reuse-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Run go mod download
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -v ./...
